Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,8 +27,17 @@ jobs:
         run: cmake --build build --config Release
 
       - name: Run tests (binary only, filter in main.cpp)
-        run: find build -type f -name gTest_test -exec {} \;
-
+        run: |
+          if [ -f ./build/gTest_test ]; then
+            ./build/gTest_test
+          elif [ -f ./build/Release/gTest_test.exe ]; then
+            ./build/Release/gTest_test.exe
+          elif [ -f ./build/Release/gTest_test ]; then
+            ./build/Release/gTest_test
+          else
+            echo "Test binary not found!"
+            exit 1
+          fi
 
   coverage:
     name: Coverage (Ubuntu only)
